config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                     sessions: 'users/sessions',
                     registrations: 'users/registrations',
                     confirmations: 'users/confirmations',
                     passwords: 'users/passwords',
                     unlocks: 'users/unlocks',
                     omniauth_callbacks: 'users/omniauth_callbacks'
                   }
  # For redirect after sign in
  get 'case_studies' => 'backend/case_studies#index', as: :user_root

  resources :case_studies, controller: 'backend/case_studies'
  resources :templates, controller: 'backend/templates'


  get ':user_url' => 'frontend/case_studies#index', as: :public_case_studies
  get ':user_url/code' => 'frontend/case_studies#code', as: :code_case_studies
  get ':user_url/:url' => 'frontend/case_studies#show', as: :public_case_study

  root 'frontend/pages#root'
end

app/models/case_study.rb
# == Schema Information
#
# Table name: case_studies
#
#  id                     :integer          not null, primary key
#  user_id                :integer
#  url                    :string
#  client                 :string
#  title                  :string
#  image_file_name        :string
#  image_content_type     :string
#  image_file_size        :integer
#  image_updated_at       :datetime
#  template_content       :text
#  template_compiled      :text
#  tile_template_content  :text
#  tile_template_compiled :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_case_studies_on_url      (url)
#  index_case_studies_on_user_id  (user_id)
#

class CaseStudy < ActiveRecord::Base
  include FindableByUrl
  SITE_URL = "#{ENV['SITE_PROTOCOL']}://#{ENV['SITE_HOST']}#{':' + ENV['SITE_PORT'] if ENV['SITE_PORT']}"

  paginates_per 10

  has_attached_file :image,
                    styles: { tile: '320x240#', huge: '1920x1080#' },
                    url: '/system/:class/:attachment/:hash.:extension',
                    hash_secret: ENV['PAPERCLIP_HASH_SECRET']
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :user

  validates_presence_of :client, :title, :image, :template_content, :tile_template_content
  validates_uniqueness_of :url, scope: :user_id

  before_validation :prepare_url
  after_validation :prepare_url_errors
  before_save :prepare_templates

  def image_url
    SITE_URL + image.url(:tile)
  end

  class << self
    def find_by_user_url!(url)
      joins(:user).where(users: {url: url})
    end
  end

private
  def prepare_url
    self.url = "#{client} #{title}".parameterize
  end

  def prepare_url_errors
    errors[:client] = I18n.t('errors.messages.already_exists', attr: 'Title and Client') if errors[:url].try(:any?)
  end

  def prepare_templates
    %i[template tile_template].each(&method(:compile_template)).each(&method(:minify_template))
  end

  def compile_template(name)
    send "#{name}_compiled=", Liquid::Template.parse(send "#{name}_content").render(attributes_for_templates)
  end

  def minify_template(name)
    premailer = Premailer.new(send("#{name}_compiled"), warn_level: Premailer::Warnings::NONE, with_html_string: true)
    send "#{name}_compiled=", Nokogiri::HTML(premailer.to_inline_css).css('body').inner_html
  end

  def attributes_for_templates
    attributes.slice(:url, :client, :title).merge(image: CodeGenerator::SITE_URL + image.url(:tile)).stringify_keys
  end
end

app/controllers/backend/application_controller.rb
module Backend
  class ApplicationController < ::ApplicationController
    before_filter :authenticate_user!
  end
end

app/controllers/backend/case_studies_controller.rb
class Backend::CaseStudiesController < Backend::ApplicationController
  inherit_resources
  has_scope :page, default: 1

  protected
  def begin_of_association_chain
    current_user
  end

  def permitted_params
    params.permit(case_study: [:image, :client, :title, :template_content, :tile_template_content])
  end

  def collection_url
    case_studies_path
  end

  def resource_url
    case_study_path(resource)
  end
end

app/controllers/backend/templates_controller.rb
class Backend::TemplatesController < Backend::ApplicationController
  inherit_resources
  actions :show
  respond_to :json
end

app/controllers/frontend/case_studies_controller.rb
class Frontend::CaseStudiesController < Frontend::ApplicationController
  inherit_resources
  actions :index, :show
  resources_configuration[:self][:finder] = :find_by_url!
  belongs_to :user, finder: :find_by_url!, param: :user_url
  has_scope :page, default: 1
  respond_to :html, :json

  before_filter :check_referer, only: [:code]

  def code
    html = collection.per(3).pluck(:tile_template_compiled).join
    render layout: false, text: html
  end

  protected
  def resource
    get_resource_ivar || set_resource_ivar(end_of_association_chain.send(method_for_find, params[:url]))
  end

  def validate_request
    u = URI(request.referer)
    u.query = u.fragment = nil
    u.path = ''
    SignUtils.sign(u.host) == params[:sign] && parent.domain == u.host rescue false
  end

  def check_referer
    return unless request.referer
    response.headers['Access-Control-Allow-Origin'] = URI.join(request.referer, '/').to_s[0..-2] if validate_request
  end

  def premailer_params
    {
      warn_level: Premailer::Warnings::NONE,
      with_html_string: true,
      remove_ids: true,
      remove_comments: true,
      include_link_tags: false,
      preserve_styles: false
    }
  end
end

app/views/backend/case_studies/_form.html.slim
.row
  .col-xs-12
    #accordion.panel-group
      .panel.panel-default
        .panel-heading
          h4.panel-title
            a data-parent="#accordion" data-toggle="collapse" href="#caseStudyTemplate" = t('.case_study_template')
        #caseStudyTemplate.panel-collapse.collapse(class="#{'in' if resource.template_content.blank?}")
          .panel-body
            .row
              - CaseStudyTemplate.all.each do |t|
                = render 'template_preview', t: t, editor: '#case_study_template_content', target: '#tileTemplate'
            .clearfix
            .reset-info = t('.reset')
      .panel.panel-default
        .panel-heading
          h4.panel-title
            a.collapsed data-parent="#accordion" data-toggle="collapse" href="#tileTemplate" = t('.tile_template')
        #tileTemplate.panel-collapse.collapse(class="#{'in' if resource.template_content.present? && resource.tile_template_content.blank?}")
          .panel-body
            .row
              - TileTemplate.all.each do |t|
                = render 'template_preview', t: t, editor: '#case_study_tile_template_content', target: '#form'
            .clearfix
            .reset-info = t('.reset')
      .panel.panel-default
        .panel-heading
          h4.panel-title
            a.collapsed data-parent="#accordion" data-toggle="collapse" href="#form" = t('.customize')
        #form.panel-collapse.collapse(class="#{'in' if resource.template_content.present? && resource.tile_template_content.present?}")
          .panel-body
            = f.input :client, placeholder: t('activerecord.attributes.case_study.client')
            = f.input :title, placeholder: t('activerecord.attributes.case_study.title')
            = f.input :image, wrapper: :horizontal_file_input, label_html: { class: 'col-md-2' },
                      hint: t('.image_hint'), required: false
            = f.input :template_content, placeholder: t('activerecord.attributes.case_study.template_content'),
                      input_html: { class: 'ace-html' }
            = f.input :tile_template_content, placeholder: t('activerecord.attributes.case_study.tile_template_content'),
                      input_html: { class: 'ace-html' }

app/views/backend/case_studies/_list_case_study.html.slim
.row.backend-list-case-study
  - resource.decorate.tap do |_resource|
    .col-xs-12.header
      .buttons-sm.dropdown
        button.btn.btn-default.btn-sm.dropdown-toggle data-toggle="dropdown"
          = t('views.common.actions')
          |&nbsp;
          = fa_icon 'caret-down'
        ul.dropdown-menu
          li = link_to t('views.common.preview'), public_case_study_path(resource.user.url, resource.url)
          li = link_to t('views.common.edit'), edit_case_study_path(resource)
          li = link_to t('views.common.delete'), case_study_path(resource), method: :delete
      h2 = link_to _resource.to_s, case_study_path(_resource)

    - if _resource.image.present?
      .col-xs-12
        .image style="background-image: url(#{_resource.image.url(:huge)})"
    .col-xs-12.body
      == _resource.template_compiled

app/views/backend/case_studies/_template_preview.html.slim
.col-xs-12.col-sm-6.col-md-4
  .thumbnail
    = image_tag t.preview.url
    .caption
      h3.text-center = t.title
      p = t.description
      a.btn.btn-primary.btn-block.choose-template(
          href="#{target}"
          data-toggle="collapse"
          data-parent="#accordion"
          data-target="#{target}"
          data-editor="#{editor}"
          data-url="#{template_path(t.id, :json)}")
        = t('.choose')

app/views/backend/case_studies/edit.html.slim
- resource.decorate.tap do |_resource|
  .container.backend-edit-case-study
    = simple_form_for resource, wrapper: :horizontal_form_without_labels, html: { class: 'form-horizontal' } do |f|
      .row
        .col-xs-12.header
          .buttons
            = f.submit t('views.common.save'), class: 'btn btn-primary'
          h1.page-header = I18n.t('views.common.edit_object', obj: _resource.to_s)

      = render 'form', f: f

app/views/backend/case_studies/index.html.slim
.container.backend-case-studies
  .row
    .col-xs-12.header
      .buttons
        = link_to t('.new_button'), new_case_study_path, class: 'btn btn-primary'
      h1.page-header = t('.title')

  - _collection = collection.to_a
  - _collection.each do |resource|
    = render 'list_case_study', resource: resource

    / Lines between elements
    - unless collection[-1] == resource
      hr

  .text-center = paginate collection

app/views/backend/case_studies/new.html.slim
- resource.decorate.tap do |_resource|

  .container.backend-new-case-study
    = simple_form_for resource, wrapper: :horizontal_form_without_labels, html: { class: 'form-horizontal' } do |f|
      .row
        .col-xs-12.header
          .buttons
            = f.submit t('views.common.save'), class: 'btn btn-primary'
          h1.page-header = I18n.t('views.common.new_object', obj: _resource.to_s)

      = render 'form', f: f

app/views/backend/case_studies/show.html.slim
.container.backend-case-study
  .row
    - resource.decorate.tap do |_resource|
      .col-xs-12.header
        .buttons
          => link_to t('views.common.preview'), public_case_study_path(resource.user.url, resource.url), class: 'btn btn-primary'
          = link_to t('views.common.edit'), edit_case_study_path(resource), class: 'btn btn-primary'
        h1.page-header = _resource.to_s

      - if _resource.image.present?
        .col-xs-12
          .image style="background-image: url(#{_resource.image.url(:huge)})"
      .col-xs-12.body
        == _resource.template_compiled