config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                     sessions: 'users/sessions',
                     registrations: 'users/registrations',
                     confirmations: 'users/confirmations',
                     passwords: 'users/passwords',
                     unlocks: 'users/unlocks',
                     omniauth_callbacks: 'users/omniauth_callbacks'
                   }
  # For redirect after sign in
  get 'case_studies' => 'backend/case_studies#index', as: :user_root

  resources :case_studies, controller: 'backend/case_studies'
  resources :templates, controller: 'backend/templates'


  get ':user_url' => 'frontend/case_studies#index', as: :public_case_studies
  get ':user_url/code' => 'frontend/case_studies#code', as: :code_case_studies
  get ':user_url/:url' => 'frontend/case_studies#show', as: :public_case_study

  root 'frontend/pages#root'
end

app/views/layouts/_flash.html.slim
- if flash.any?
  .container
    .row.flashes
      .col-xs-12
        - if flash[:notice].present?
          .alert.alert-success
            button type="button" class="close" data-dismiss="alert" ×
            = flash[:notice]
        - if flash[:alert].present?
          .alert.alert-warning
            button type="button" class="close" data-dismiss="alert" ×
            = flash[:alert]
        - if flash[:error].present?
          .alert.alert-danger
            button type="button" class="close" data-dismiss="alert" ×
            = flash[:error]

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target="#navbar-collapse" data-toggle="collapse" type="button"
        span.sr-only = t('.toggle')
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to t('.title'), root_path, class: 'navbar-brand'
    #navbar-collapse.collapse.navbar-collapse
      /ul.nav.navbar-nav
        /li.active
          a href="#"
            | Link
            span.sr-only (current)
        /li
          a href="#"  Link
        /li.dropdown
          a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
            | Dropdown
            span.caret
          ul.dropdown-menu role="menu"
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider
            li
              a href="#"  Separated link
            li.divider
            li
              a href="#"  One more separated link
      /form.navbar-form.navbar-left role="search"
        .form-group
          input.form-control placeholder="Search" type="text" /
        button.btn.btn-default type="submit"  Submit
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          = li controller?(:'backend/case_studies') do
            = link_to t('.case_studies'), case_studies_path
          = li controller?(:'users/registrations') do
            = link_to t('.cabinet'), edit_user_registration_path

          li = link_to t('.log_out'), destroy_user_session_path, method: :delete
        - else
          = li controller?(:'users/sessions') && action?(:new, :create) do
            = link_to t('users.sessions.common.sign_in'), new_user_session_path
          = li controller?(:'users/registrations') && action?(:new, :create) do
            = link_to t('users.sessions.common.sign_up'), new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testify</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>